### ISSUE TITLE
FE Requested response for Halaqaat and Events

### ISSUE THREAD

**Issue by Yusadolat** [muslimbuilders/halaqaat-server#22]
Hi @kennie-larkson 

Below is the data format request when FE requested for single Halaqaat and Events. 

`name,`
`address,`
`lat,`
`lon,`
`type: halqah | event,`
`occurrence: weekly | biweekly | monthly,`
`time,`

Lemme know if you have any question.

**Comment by kennie-larkson** [comment]
Hey boss
I don’t understand the requirements of the task

**Comment by Yusadolat** [comment]
That's the response to send when the client request an Halqah or Event. You are not to send all halqah or event data

**Comment by kennie-larkson** [comment]
Hey boss, 
Hope you are doing well
My bad, but this expected response does not mimic the structure of our models in some instances e.g lat, lon, occurrence 
Could you shed more light please 

Thanks

**Comment by Yusadolat** [comment]
That was very correct, Occurrence was not part of the model. So you have to add it. As for lat and on, it the coordinates field on the model. I hope that helps?
Cheers!

**Comment by kennie-larkson** [comment]
Meanwhile I think I might have to PULL
Which branch should I PULL from ?
Master or Develop?

**Comment by Yusadolat** [comment]
Develop as usual

**Comment by kennie-larkson** [comment]
Hi Chief,
Got this issue complaining about models and the import keyword in the file psst
![git error](https://user-images.githubusercontent.com/32939546/120432056-428a1b00-c371-11eb-90d1-7af54fee02c2.PNG)

**Comment by Yusadolat** [comment]
You might need to fix the conflict first. I can't reproduce it from here


![Screen Shot 2021-06-02 at 7 14 25 AM](https://user-images.githubusercontent.com/10975011/120432633-1b801900-c372-11eb-97b6-ef8ca23efdd5.png)

**Comment by Yusadolat** [comment]
You probably have Unstaged files before you pull...

**Comment by kennie-larkson** [comment]
Yes .env is the only Unstaged file and I believe that is because I do not want to include it in my commit or whatever lol

**Comment by kennie-larkson** [comment]
okay i have added it and sorted

thanks for the heads up

**Comment by kennie-larkson** [comment]
Boss I still have issues with adding data to my database for testing these routes. Remember the other time I mentioned it. I really cannot seem to figure out what I omit in the structure of the model while populating the collection. 
 :( :(

**Comment by kennie-larkson** [comment]
![rest client error](https://user-images.githubusercontent.com/32939546/120461468-f0a5bd00-c391-11eb-9e0c-e313e9528dcd.PNG)
I am trying to use REST Client to test this APIs but I get that error on vs code

**Comment by kennie-larkson** [comment]
Could that have to do with the update you fixed on mongo the other day?
Do I need to update my mongo package in package.json?

**Comment by Yusadolat** [comment]
Who uses VScode Rest client to test APIs. Baba Use postman. I can't even figure out what's wrong here

**Comment by kennie-larkson** [comment]
Postman couldn’t either

**Comment by kennie-larkson** [comment]
I used Postman also  and the error was "could not send request"
I really don't know what I am missing.
I mean do you think it could be that Mongoose upgrade you did the other day? Perhaps I need to upgrade Mongoose or something. Really at sea here chief.

**Comment by Yusadolat** [comment]
#24
